//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViajaPeru.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_VIAJAPERUEntities : DbContext
    {
        public BD_VIAJAPERUEntities()
            : base("name=BD_VIAJAPERUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_comprobante> tb_comprobante { get; set; }
        public virtual DbSet<tb_gturistica> tb_gturistica { get; set; }
        public virtual DbSet<tb_hoteles> tb_hoteles { get; set; }
        public virtual DbSet<tb_itinerario> tb_itinerario { get; set; }
        public virtual DbSet<tb_mediopago> tb_mediopago { get; set; }
        public virtual DbSet<tb_mediotrans> tb_mediotrans { get; set; }
        public virtual DbSet<tb_movilidad> tb_movilidad { get; set; }
        public virtual DbSet<tb_paquetes> tb_paquetes { get; set; }
        public virtual DbSet<tb_tipo_usuario> tb_tipo_usuario { get; set; }
        public virtual DbSet<tb_usuario> tb_usuario { get; set; }
    }
}
