//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViajaPeru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_paquetes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_paquetes()
        {
            this.tb_itinerario = new HashSet<tb_itinerario>();
        }
    
        public int id_paquete { get; set; }
        public decimal precio_paquete { get; set; }
        public Nullable<int> id_hotel { get; set; }
        public Nullable<int> id_movilidad { get; set; }
        public Nullable<int> id_gturistica { get; set; }
    
        public virtual tb_gturistica tb_gturistica { get; set; }
        public virtual tb_hoteles tb_hoteles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_itinerario> tb_itinerario { get; set; }
        public virtual tb_movilidad tb_movilidad { get; set; }
    }
}
